# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2b4747fcedf6870254a36eb57d95620ff53ca352a36dca0f708f8ae0d090d7054c8adb2f206138670cac8a87e4f26d93dc0f27a8b5d714eefd30cf8800e128d

test:
  secret_key_base: 3cf687e189a1fde1bf432ab077e0408f058f27739eed78cce2ac558a258e4ba6e6d68e02696c658b8eb0704a65b73532104fc65310fdd60460ec6b33465c5bc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
